[Logging]
  Disable = false
  File = "/tmp/meson/ping/ping.log"
  Level = "DEBUG"

[UpstreamProxy]
  Type = "none"
  Network = ""
  Address = ""
  User = ""
  Password = ""

[Debug]
  DisableDecoyTraffic = true
  SessionDialTimeout = 120000000
  InitialMaxPKIRetrievalDelay = 30
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 100

[Katzenmint]
  ChainID = "katzenmint-chain-71DRoz"
  PrimaryAddress = "tcp://104.131.108.194:26657"
  WitnessesAddresses = ["104.131.108.194:26657"]
  DatabaseName = "ping"
  DatabaseDir = "/tmp/meson/ping/db"
  RPCAddress = "tcp://104.131.108.194:26657"
  [Katzenmint.TrustOptions]
    Period = "10m0s"
    Height = 4736
    Hash = [88, 226, 174, 145, 65, 83, 45, 6, 61, 77, 28, 165, 120, 168, 55, 29, 153, 232, 251, 168, 70, 14, 71, 136, 159, 205, 51, 138, 183, 203, 213, 132]
