[Logging]
  Disable = false
  File = "/tmp/meson/ping/ping.log"
  Level = "DEBUG"

[UpstreamProxy]
  Type = "none"
  Network = ""
  Address = ""
  User = ""
  Password = ""

[Debug]
  DisableDecoyTraffic = true
  SessionDialTimeout = 120000000
  InitialMaxPKIRetrievalDelay = 30
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 100

[Katzenmint]
  ChainID = "katzenmint-chain-71DRoz"
  PrimaryAddress = "tcp://104.131.108.194:26657"
  WitnessesAddresses = ["104.131.108.194:26657"]
  DatabaseName = "ping"
  DatabaseDir = "/tmp/meson/ping/db"
  RPCAddress = "tcp://104.131.108.194:26657"
  [Katzenmint.TrustOptions]
    Period = "10m0s"
    Height = 1185
    Hash = [59, 70, 121, 86, 126, 42, 194, 225, 124, 126, 225, 208, 191, 127, 121, 1, 38, 171, 135, 142, 9, 184, 77, 24, 119, 162, 65, 180, 41, 161, 19, 79]
