[Logging]
  Disable = false
  File = "/tmp/meson/ping/ping.log"
  Level = "DEBUG"

[UpstreamProxy]
  Type = "none"
  Network = ""
  Address = ""
  User = ""
  Password = ""

[Debug]
  DisableDecoyTraffic = true
  SessionDialTimeout = 1200000
  InitialMaxPKIRetrievalDelay = 30
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 100

[Katzenmint]
  ChainID = "katzenmint-chain-71DRoz"
  PrimaryAddress = "tcp://127.0.0.1:21483"
  WitnessesAddresses = ["127.0.0.1:21483"]
  DatabaseName = "ping"
  DatabaseDir = "/tmp/meson/ping/db"
  RPCAddress = "tcp://127.0.0.1:21483"
  [Katzenmint.TrustOptions]
    Period = 600000000000
    Height = 146
    Hash = [9, 65, 87, 95, 1, 76, 214, 5, 161, 121, 221, 32, 22, 203, 102, 79, 243, 2, 234, 0, 158, 105, 249, 149, 45, 129, 79, 155, 81, 50, 213, 22]
