[Logging]
  Disable = false
  File = "/tmp/meson/ping/ping.log"
  Level = "DEBUG"

[UpstreamProxy]
  Type = "none"
  Network = ""
  Address = ""
  User = ""
  Password = ""

[Debug]
  DisableDecoyTraffic = true
  SessionDialTimeout = 120000000
  InitialMaxPKIRetrievalDelay = 30
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 100

[Katzenmint]
  ChainID = "katzenmint-chain-71DRoz"
  PrimaryAddress = "tcp://127.0.0.1:21483"
  WitnessesAddresses = ["127.0.0.1:21483"]
  DatabaseName = "ping"
  DatabaseDir = "/tmp/meson/ping/db"
  RPCAddress = "tcp://127.0.0.1:21483"
  [Katzenmint.TrustOptions]
    Period = 600000000000
    Height = 294
    Hash = [228, 74, 124, 161, 12, 51, 216, 93, 239, 171, 187, 221, 198, 232, 28, 227, 13, 40, 221, 31, 14, 23, 67, 231, 227, 140, 213, 121, 153, 151, 138, 181]
