key_store_path = "./keystore"
meson_setting_path = "./client.example.toml"

[Chain]
  [Chain.5]
    Ticker = "gor"
    Endpoint = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
  [Chain.4]
    Ticker = "rin"
    Endpoint = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
  [Chain.42]
    Ticker = "kov"
    Endpoint = "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"