[Logging]
  Disable = false
  File = "/tmp/meson/ping/ping.log"
  Level = "DEBUG"

[UpstreamProxy]
  Type = "none"
  Network = ""
  Address = ""
  User = ""
  Password = ""

[Debug]
  DisableDecoyTraffic = true
  SessionDialTimeout = 120000000
  InitialMaxPKIRetrievalDelay = 30
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 100

[Katzenmint]
  ChainID = "katzenmint-chain-71DRoz"
  PrimaryAddress = "tcp://127.0.0.1:21483"
  WitnessesAddresses = ["127.0.0.1:21483"]
  DatabaseName = "ping"
  DatabaseDir = "/tmp/meson/ping/db"
  RPCAddress = "tcp://127.0.0.1:21483"
  [Katzenmint.TrustOptions]
    Period = 600000000000
    Height = 376
    Hash = [54, 48, 119, 7, 121, 217, 46, 255, 107, 187, 11, 14, 130, 202, 133, 64, 94, 64, 135, 160, 138, 28, 231, 86, 226, 63, 242, 102, 121, 89, 19, 13]
